########################################################################################################################
# DOCKER IMAGES
###############

image_build_environment: &image_build_environment
  image: alpine:latest

########################################################################################################################
# JOBS AND WORKFLOWS
####################

version: 2
jobs:
  bootstrap:
    parallelism: 1
    docker:
      - <<: *image_build_environment
    steps:
      - run: sleep 1
  package:
    parallelism: 1
    docker:
      - <<: *image_build_environment
    steps:
      - run: sleep 1
  test:
    parallelism: 1
    docker:
      - <<: *image_build_environment
    steps:
      - run: sleep 1
  deploy:
    parallelism: 1
    docker:
      - <<: *image_build_environment
    steps:
      - run: sleep 1
  notify:
    parallelism: 1
    docker:
      - <<: *image_build_environment
    steps:
      - run:
          name: Install jq and curl
          command: |
            apk update \
              && apk add jq curl \
              && rm -rf /var/cache/apk/* \
              && rm -rf /var/cache/curl/*
      - run:
          name: Issue request to notification endpoint
          command: |
            curl -H "Accept: application/json" \
                 -u ${CIRCLE_API_TOKEN}: \
                 https://circleci.com/api/v1.1/project/github/${CIRCLE_PROJECT_USERNAME}/${CIRCLE_PROJECT_REPONAME}/${CIRCLE_BUILD_NUM} \
              | jq '{ payload: (. * { "status": "success" }) }' \
              | curl -H "Content-Type: application/json" -X POST -d @- https://hookb.in/Klww8jkp?foo=bar
workflows:
  version: 2
  do-it-all:
    jobs:
      - bootstrap
      - package:
          requires:
            - bootstrap
      - test:
          requires:
            - bootstrap
      - deploy:
          requires:
            - test
            - package
      - notify:
          requires:
            - deploy
